version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            # - APP_KEY=base64:$(php artisan key:generate --show)
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: laravel_db
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - laravel_network
        ports:
            - "5432:5432"

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        ports:
            - "8080:80"
        depends_on:
            - app

volumes:
    pgdata:

networks:
    laravel_network:
        driver: bridge
